package com.pentadigital.calculator.utils

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.os.Environment
import android.widget.Toast
import com.pentadigital.calculator.R
import com.pentadigital.calculator.viewmodels.GoalPlannerState
import com.pentadigital.calculator.viewmodels.LoanPrepaymentState
import java.io.File
import java.io.FileOutputStream
import java.io.IOException
import java.text.NumberFormat
import java.util.Locale

object PdfGenerator {

    fun generateLoanPrepaymentPdf(context: Context, state: LoanPrepaymentState): File? {
        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create() // A4 size in points
        val page = pdfDocument.startPage(pageInfo)
        val canvas = page.canvas
        val paint = Paint()

        // Formatting
        val currencyFormat = NumberFormat.getCurrencyInstance(Locale("en", "IN"))
        val titlePaint = Paint().apply {
            color = Color.BLACK
            textSize = 24f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }
        val headerPaint = Paint().apply {
            color = Color.DKGRAY
            textSize = 16f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }
        val textPaint = Paint().apply {
            color = Color.BLACK
            textSize = 14f
        }
        val valuePaint = Paint().apply {
            color = Color.BLACK
            textSize = 14f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            textAlign = Paint.Align.RIGHT
        }

        var y = 50f
        val margin = 40f
        val pageWidth = pageInfo.pageWidth.toFloat()
        val valueX = pageWidth - margin

        // Title
        canvas.drawText("Loan Prepayment Analysis", margin, y, titlePaint)
        y += 40f

        // Section: Inputs
        canvas.drawText("Loan Details", margin, y, headerPaint)
        y += 30f
        
        drawRow(canvas, "Loan Amount", currencyFormat.format(state.loanAmount), margin, valueX, y, textPaint, valuePaint)
        y += 25f
        drawRow(canvas, "Interest Rate", "${state.interestRate}%", margin, valueX, y, textPaint, valuePaint)
        y += 25f
        drawRow(canvas, "Tenure", "${state.tenureYears} Years", margin, valueX, y, textPaint, valuePaint)
        y += 25f
        drawRow(canvas, "Monthly Prepayment", currencyFormat.format(state.monthlyPrepayment), margin, valueX, y, textPaint, valuePaint)
        y += 25f
        drawRow(canvas, "Lumpsum Prepayment", currencyFormat.format(state.lumpsumPrepayment), margin, valueX, y, textPaint, valuePaint)
        y += 40f

        // Section: Results
        canvas.drawText("Results", margin, y, headerPaint)
        y += 30f

        drawRow(canvas, "Total Savings", currencyFormat.format(state.interestSaved), margin, valueX, y, textPaint, valuePaint)
        y += 25f
        drawRow(canvas, "Time Saved", "${state.timeSavedMonths} Months", margin, valueX, y, textPaint, valuePaint)
        y += 25f
        drawRow(canvas, "Original Interest", currencyFormat.format(state.originalTotalInterest), margin, valueX, y, textPaint, valuePaint)
        y += 25f
        drawRow(canvas, "New Interest", currencyFormat.format(state.newTotalInterest), margin, valueX, y, textPaint, valuePaint)
        y += 25f
        drawRow(canvas, "Original Tenure", "${state.originalTenureMonths} Months", margin, valueX, y, textPaint, valuePaint)
        y += 25f
        drawRow(canvas, "New Tenure", "${state.newTenureMonths} Months", margin, valueX, y, textPaint, valuePaint)

        // Footer
        y = pageInfo.pageHeight - 40f
        val footerPaint = Paint().apply {
            color = Color.GRAY
            textSize = 12f
            textAlign = Paint.Align.CENTER
        }
        canvas.drawText("Generated by Calculator App", pageWidth / 2, y, footerPaint)

        pdfDocument.finishPage(page)

        val file = File(context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS), "LoanPrepayment_${System.currentTimeMillis()}.pdf")
        
        try {
            pdfDocument.writeTo(FileOutputStream(file))
            Toast.makeText(context, "PDF Saved: ${file.absolutePath}", Toast.LENGTH_LONG).show()
        } catch (e: IOException) {
            e.printStackTrace()
            Toast.makeText(context, "Error saving PDF: ${e.message}", Toast.LENGTH_SHORT).show()
            return null
        } finally {
            pdfDocument.close()
        }
        return file
    }

    fun generateGoalPlannerPdf(context: Context, state: GoalPlannerState): File? {
        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create()
        val page = pdfDocument.startPage(pageInfo)
        val canvas = page.canvas

        // Formatting
        val currencyFormat = NumberFormat.getCurrencyInstance(Locale("en", "IN"))
        val titlePaint = Paint().apply {
            color = Color.BLACK
            textSize = 24f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }
        val headerPaint = Paint().apply {
            color = Color.DKGRAY
            textSize = 16f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
        }
        val textPaint = Paint().apply {
            color = Color.BLACK
            textSize = 14f
        }
        val valuePaint = Paint().apply {
            color = Color.BLACK
            textSize = 14f
            typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)
            textAlign = Paint.Align.RIGHT
        }

        var y = 50f
        val margin = 40f
        val pageWidth = pageInfo.pageWidth.toFloat()
        val valueX = pageWidth - margin

        // Title
        canvas.drawText("Investment Goal Plan", margin, y, titlePaint)
        y += 40f

        // Section: Inputs
        canvas.drawText("Goal Details", margin, y, headerPaint)
        y += 30f

        drawRow(canvas, "Target Amount", currencyFormat.format(state.targetAmount), margin, valueX, y, textPaint, valuePaint)
        y += 25f
        drawRow(canvas, "Time Period", "${state.timePeriodYears} Years", margin, valueX, y, textPaint, valuePaint)
        y += 25f
        drawRow(canvas, "Expected Return", "${state.expectedReturnRate}%", margin, valueX, y, textPaint, valuePaint)
        y += 40f

        // Section: Results
        canvas.drawText("Required Investment", margin, y, headerPaint)
        y += 30f

        drawRow(canvas, "Monthly Investment (SIP)", currencyFormat.format(state.requiredMonthlyInvestment), margin, valueX, y, textPaint, valuePaint)
        y += 25f
        drawRow(canvas, "Total Investment", currencyFormat.format(state.totalInvestment), margin, valueX, y, textPaint, valuePaint)
        y += 25f
        drawRow(canvas, "Total Returns", currencyFormat.format(state.totalReturns), margin, valueX, y, textPaint, valuePaint)

        // Footer
        y = pageInfo.pageHeight - 40f
        val footerPaint = Paint().apply {
            color = Color.GRAY
            textSize = 12f
            textAlign = Paint.Align.CENTER
        }
        canvas.drawText("Generated by Calculator App", pageWidth / 2, y, footerPaint)

        pdfDocument.finishPage(page)

        val file = File(context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS), "GoalPlan_${System.currentTimeMillis()}.pdf")

        try {
            pdfDocument.writeTo(FileOutputStream(file))
            Toast.makeText(context, "PDF Saved: ${file.absolutePath}", Toast.LENGTH_LONG).show()
        } catch (e: IOException) {
            e.printStackTrace()
            Toast.makeText(context, "Error saving PDF: ${e.message}", Toast.LENGTH_SHORT).show()
            return null
        } finally {
            pdfDocument.close()
        }
        return file
    }

    private fun drawRow(canvas: Canvas, label: String, value: String, x: Float, valueX: Float, y: Float, labelPaint: Paint, valuePaint: Paint) {
        canvas.drawText(label, x, y, labelPaint)
        canvas.drawText(value, valueX, y, valuePaint)
    }
}
